# =======================================================================================
#
#         /$$$$$$$$ /$$   /$$ /$$   /$$ /$$$$$$$  /$$$$$$ /$$   /$$  /$$$$$$ 
#        | $$_____/| $$  | $$| $$$ | $$| $$__  $$|_  $$_/| $$$ | $$ /$$__  $$
#        | $$      | $$  | $$| $$$$| $$| $$  \ $$  | $$  | $$$$| $$| $$  \__/
#        | $$$$$   | $$  | $$| $$ $$ $$| $$  | $$  | $$  | $$ $$ $$| $$ /$$$$
#        | $$__/   | $$  | $$| $$  $$$$| $$  | $$  | $$  | $$  $$$$| $$|_  $$
#        | $$      | $$  | $$| $$\  $$$| $$  | $$  | $$  | $$\  $$$| $$  \ $$
#        | $$      |  $$$$$$/| $$ \  $$| $$$$$$$/ /$$$$$$| $$ \  $$|  $$$$$$/
#        |__/       \______/ |__/  \__/|_______/ |______/|__/  \__/ \______/ 
#
# =======================================================================================
#                        Display a `Sponsor` button in your repository
#        to increase the visibility of funding options for your open source project.
#  Author: Fabio Craig Wimmer Florey                                      Version: 0.0.1
# =======================================================================================
github: FabioFlorey
custom: # Replace with up to 4 custom sponsorships URLs, e.g.: [URL1, URL2]
