# =======================================================================================
#
#     /$$$$$  /$$$$$$$ /$$$$$$$ /$$   /$$ /$$$$$$  /$$$$$$ /$$$$$  /$$      /$$ /$$      
#    /$$_  $$| $$____/|_  $$__/| $$  | $$| $$_  $$|_  $$_//$$_  $$| $$$    /$$$| $$      
#   | $$ \__/| $$       | $$   | $$  | $$| $$ \ $$  | $$ | $$ \ $$| $$$$  /$$$$| $$      
#   |  $$$$$ | $$$$$    | $$   | $$  | $$| $$$$$$/  | $$ | $$ | $$| $$ $$/$$ $$| $$      
#    \___  $$| $$__/    | $$   | $$  | $$| $$___/   | $$ | $$ | $$| $$  $$$| $$| $$      
#    /$$ \ $$| $$       | $$   | $$  | $$| $$       | $$ | $$ | $$| $$\  $ | $$| $$      
#   |  $$$$$/| $$$$$$$  | $$   |  $$$$$$/| $$ /$$   | $$ |  $$$$$/| $$ \/  | $$| $$$$$$
#    \_____/ |_______/  |__/    \______/ |__/|__/   |__/  \_____/ |__/     |__/|______/
#
# =======================================================================================
#  Author: Fabio Craig Wimmer Florey                                      Version: 0.0.1
# =======================================================================================

name             = 'Project'
description      = 'Brief description'
version          = '0.0.1'
license          = 'MIT-0'
url              = 'https://github.com/FabioFlorey/'
download_url     = 'https://github.com/FabioFlorey/'

content_type = 'text/markdown'

author           = 'Fabio Craig Wimmer Florey'
author_email     = '<email@domain.com>'
maintainer       = ''
maintainer_email = ''

keywords         = [
                    ''
                   ]

classifiers      = [
                    'Programming Language :: Python',
                    'Programming Language :: Python :: 3 :: Only'
                   ]

python_requires  = '>=3.10'
install_requires = [
                    # 
                   ]
[extras_require]
# extra_name       = [
#                     # 'module'
#                    ]

[entry_points]
console_scripts = [
                    # 'module:function'
                  ]
