name: Report a bug
description: something went wrong
body:
  - type: markdown
    attributes:
      value: |
          body
  - type: input
    id: OS
    attributes:
      label: OS
      description: Please, be as specific as possible
      placeholder: |
        -  Windows 10 Pro, version 21H1, build 19043
        - macOS Big Sur, version 11.2.3, build 20D91
        - Ubuntu 20.04 LTS, version Focal Fossa, build 5.4.0-72
    validations:
      required: true
  - type: textarea
    id: freeform
    attributes:
      label: describe your issue
      placeholder: 'I was doing ... I ran ... I expected ... I got ...'
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Error StackTrace 
      description: <sub> The stacktrace will autoredender as code, no need for backticks </sub>
      placeholder: |
        `Publish your error stacktrace here`
      render: bash
    validations:
      required: false