# =============================================================================
# Project
# =============================================================================
# Docs Report
# -----------------------------------------------------------------------------
# Issue Template for GitHub
#
# :Authors: Fabio Craig Wimmer Florey <fabioflorey@icloud.com>
# :Version: 0.0.1
# :License: MIT-0
name: Documents
description:  📚 Improvements or addition to documentation