# =======================================================================================
#                 $$$$$$\  $$$$$$\ $$$$$$$$\ $$\   $$\ $$\   $$\ $$$$$$$\           
#                $$  __$$\ \_$$  _|\__$$  __|$$ |  $$ |$$ |  $$ |$$  __$$\          
#                $$ /  \__|  $$ |     $$ |   $$ |  $$ |$$ |  $$ |$$ |  $$ |         
#                $$ |$$$$\   $$ |     $$ |   $$$$$$$$ |$$ |  $$ |$$$$$$$\ |         
#                $$ |\_$$ |  $$ |     $$ |   $$  __$$ |$$ |  $$ |$$  __$$\          
#                $$ |  $$ |  $$ |     $$ |   $$ |  $$ |$$ |  $$ |$$ |  $$ |         
#                \$$$$$$  |$$$$$$\    $$ |   $$ |  $$ |\$$$$$$  |$$$$$$$  |         
#                 \______/ \______|   \__|   \__|  \__| \______/ \_______/          
#            $$$$$$\   $$$$$$\ $$$$$$$$\ $$$$$$\  $$$$$$\  $$\   $$\  $$$$$$\  
#           $$  __$$\ $$  __$$\\__$$  __|\_$$  _|$$  __$$\ $$$\  $$ |$$  __$$\ 
#           $$ /  $$ |$$ /  \__|  $$ |     $$ |  $$ /  $$ |$$$$\ $$ |$$ /  \__|
#           $$$$$$$$ |$$ |        $$ |     $$ |  $$ |  $$ |$$ $$\$$ |\$$$$$$\  
#           $$  __$$ |$$ |        $$ |     $$ |  $$ |  $$ |$$ \$$$$ | \____$$\ 
#           $$ |  $$ |$$ |  $$\   $$ |     $$ |  $$ |  $$ |$$ |\$$$ |$$\   $$ |
#           $$ |  $$ |\$$$$$$  |  $$ |   $$$$$$\  $$$$$$  |$$ | \$$ |\$$$$$$  |
#           \__|  \__| \______/   \__|   \______| \______/ \__|  \__| \______/ 
# =======================================================================================
#               Create a project artifact if the CI action is succesful
#  Author: Fabio Craig Wimmer Florey                                      Version: 0.0.1
# =======================================================================================

name: Continuous Delivery

on:
   workflow_run:
     workflows: ["Continuous Integration"]
     types: [completed] #requested

jobs:
  Successful_CI:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Build package
      run: |
        python -m pip install wheel
        python -m setup sdist bdist_wheel
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: built-package
        path: dist/*

  Failed_CI:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "Continous Integration failed"


