# =============================================================================
# Project
# =============================================================================
# Continuous Integration
# -----------------------------------------------------------------------------
# Configuration file for GitHub Actions.
#
# :Authors: Fabio Craig Wimmer Florey <fabioflorey@icloud.com>
# :Version: 0.0.1s
# :License: MIT-0


name: Continuous Integration

on:
  push:
    branches:
      ['master'] # I know it's main, but I don't want to trigger it for now! :P

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tests/test-requirements.txt
    - name: Lint the codebase with Black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./project"
        version: "~= 22.0"
    - name: Test with tox
      run: tox
    - name: Upload report on CodeCoverage
      if: success()
      uses: codecov/codecov-action@v3
      with:
        file: ./tests/coverage.xml
        token: ${{ secrets.CODE_COVERAGE }}
    
  