# =======================================================================================
#                 $$$$$$\  $$$$$$\ $$$$$$$$\ $$\   $$\ $$\   $$\ $$$$$$$\           
#                $$  __$$\ \_$$  _|\__$$  __|$$ |  $$ |$$ |  $$ |$$  __$$\          
#                $$ /  \__|  $$ |     $$ |   $$ |  $$ |$$ |  $$ |$$ |  $$ |         
#                $$ |$$$$\   $$ |     $$ |   $$$$$$$$ |$$ |  $$ |$$$$$$$\ |         
#                $$ |\_$$ |  $$ |     $$ |   $$  __$$ |$$ |  $$ |$$  __$$\          
#                $$ |  $$ |  $$ |     $$ |   $$ |  $$ |$$ |  $$ |$$ |  $$ |         
#                \$$$$$$  |$$$$$$\    $$ |   $$ |  $$ |\$$$$$$  |$$$$$$$  |         
#                 \______/ \______|   \__|   \__|  \__| \______/ \_______/          
#            $$$$$$\   $$$$$$\ $$$$$$$$\ $$$$$$\  $$$$$$\  $$\   $$\  $$$$$$\  
#           $$  __$$\ $$  __$$\\__$$  __|\_$$  _|$$  __$$\ $$$\  $$ |$$  __$$\ 
#           $$ /  $$ |$$ /  \__|  $$ |     $$ |  $$ /  $$ |$$$$\ $$ |$$ /  \__|
#           $$$$$$$$ |$$ |        $$ |     $$ |  $$ |  $$ |$$ $$\$$ |\$$$$$$\  
#           $$  __$$ |$$ |        $$ |     $$ |  $$ |  $$ |$$ \$$$$ | \____$$\ 
#           $$ |  $$ |$$ |  $$\   $$ |     $$ |  $$ |  $$ |$$ |\$$$ |$$\   $$ |
#           $$ |  $$ |\$$$$$$  |  $$ |   $$$$$$\  $$$$$$  |$$ | \$$ |\$$$$$$  |
#           \__|  \__| \______/   \__|   \______| \______/ \__|  \__| \______/ 
# =======================================================================================
#             Define GitHub Actions to run automated tests on the codebase.
#  Author: Fabio Craig Wimmer Florey                                      Version: 0.0.1
# =======================================================================================

name: Continuous Integration

on:
  push:
    branches:
      ['main']

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tests/test-requirements.txt
    - name: Test with tox
      run: tox
    - name: Upload report on CodeCoverage
      if: success()
      uses: codecov/codecov-action@v3
      with:
        file: ./tests/coverage.xml
        token: ${{ secrets.CODE_COVERAGE }}
